### ISSUE TITLE
Going public

### ISSUE THREAD

**Issue by glebm** [thredded/thredded#141]
We need these for going public:

* [x] Sort out permissions. #126 #138
* [x] Fix avatar support. #137
* [x] Scope the styles. #81 
* [x] Extract DB text search into a gem, making thredded DB-agnostic. #172
* [x] Squash the migrations. #167
* [x] Create a thredded GitHub org? With these repos:
    * [x] `thredded` - from this repo.
    * [x] `thredded.com` - the main website, also a demo app of the integration.

Also, to consider:
* `blog.thredded.com` - release blog, a simple static site with disqus perhaps, like [my blog](http://blog.glebm.com/). Alternatively, the blog can run on `thredded.com` with something like the [blogit](https://github.com/KatanaCode/blogit) Rails engine.
* `thredded-theme-bootstrap3` - a bootstrap 3 theme (based on [the wiki page](https://github.com/jayroh/thredded/wiki/Bootstrap-Sass-Styles)).

Is anything missing?

* * *

Announcement checklist:

* [x] Update CHANGELOG to very latest status
* [x] Update README
* [x] freeze, tag 0.3.0, and publish to rubygems (thursday?)
* [x] thredded.com migrated to latest gem. (the meta messageboard should be cleaned up and contain some sort of announcement topic)
* [x] Analytics code in demo app. Mixpanel? Google Analytics?
* [x] Rake task (for running nightly) that truncates thredded tables and re-seeds.
* [x] Upgrade Heroku to one of the paid tiers and scale up before release, because the free tier won't survive HN traffic.
* [ ] Copy for submitting to:
  * [x] HN
  * [x] /r/ruby
  * [ ] /r/rails
  * [x] Ruby5
  * [x] RubyWeekly
  * [ ] RubyFlow
  * [ ] RubyDaily
  * [x] [MetaRuby](http://metaruby.com/)
* [ ] Joel, Gleb, Shaun, Jim (saturnflyer), anyone w/project history tweeting ... ask friends to tweet?

**Comment by jayroh** [comment]
It certainly isn't necessary for a public launch or push but soon after I would put some bumped priority on the following two things:

1. Pushing a lot of the exposed objects from the controller -> view layer into a common sense interface that doesn't rely on knowing what the instance variables are per controller and action. Eg: If you're on a messageboards controller you know that there's a `messageboard` object ... if you're on a page with a form adding/editing a messageboard object, you know there's a `messageboard_form` object. I would consider these something akin to view models. These aren't something I would regularly consider for a normal project but when it comes to open source ... if I was going to work on customizing a view layer to an engine I would love to know that I could EASILY guess what the objects -- or better yet, one object -- are between the view and controller. Which leads me to...
2. Comprehensive documentation. Yard docs outlining what those view models, and other classes, consist of would be fantastic.

At best those are nice-to-haves -- at worst maybe a bit anal. But if this were to ever get any sort of wider spread adoption I could see those being pain points.

**Comment by jayroh** [comment]
Been thinking a lot lately about a concerted push to give this a legitimate road-map and plan for future releases leading up to a 1.0 release.

I admit I've been completely lax and blazé when it comes to both cutting gem versions, and maintaining even a remote semblance of semver. The recent juggling of work, a side project, etc, has put thredded well on the back-burner unfortunately. That doesn't mean there shouldn't be some sort of direction though. If I, or others, can't write code every day maybe we can help steer it in the right direction.

Anyway - If there are must-haves that aren't addressed here, or are peppered throughout the rest of the issues, I would love to aggregate them here and start drafting a roadmap for where this should go. I'll come back here with some further thoughts as they come to me.

**Comment by jayroh** [comment]
One must-have I would start with is to pull both the PG and MySQL search implementations out entirely to their own gems so that they are not part of the core thredded gem. If there is an interface we could agree on that serves as the gateway to an adapter system, I would be very very happy with that.

**Comment by glebm** [comment]
While splitting PG and MySQL search code is trivial, as they already adhere to a common interface. Splitting overall support for these can be very tricky because of migrations. Not sure it's worth the effort at this stage, but the amount of effort will be clearer once we squash the migrations.

**Comment by jayroh** [comment]
At this point it's less about the implementation and more about the dependencies. One thing I always think about when it comes to this project is simplicity. I would like to strive for simplicity. In its core it currently supports both PG and MySQL, and, for all intents and purposes, not SQLite. Needing to have mysql installed just to test the gem (I have no other need for mysql here) is something I would prefer not having to do.

I personally don't care much about SQLite, but it *would* be nice to pull this repo down and just run `rake db:migrate` without needing anything else. There are ancillary benefits to this, as well -- example: smaller test matrix.

**Comment by glebm** [comment]
So, I'm thinking of a gem, let's call it db_text_search, that would provide the following:

1. `CaseInsensitiveStringFinder`

    ```ruby
    DbTextSearch::CaseInsensitiveStringFinder.new(scope, column).find(string)
    ```

2. `FullTextSearcher`

    ```ruby
    DbTextSearch::FullTextSearcher.supported?(connection)
    DbTextSearch::FullTextSearcher.search_conds(column, terms) 
      # => [where SQL fragment, ?-values]
    ```

3. `Migration`

    ```ruby
    DbTextSearch::Migration.add_index table, column
    ```

This would be a very basic gem, without lots of bells and whistles, but it fully covers the needs of thredded, and can be improved independently.

The only remaining issue is the 191 maximum indexed string length limit on MySQL (for slugs). I suggest we go with the lowest common denominator here and just do 191 always (currently it's 191 for MySQL and 255 for Postgres).

**Comment by jayroh** [comment]
I really like that idea! And I see you've already started working on it, haha. Go Gleb!

**Comment by jayroh** [comment]
As you can tell, I've moved the main repo to the thredded organization. So if you want to change your remote origins accordingly, I would encourage you to do so.

cc @TheDudeWithTheThing @glebm @cgunther

**Comment by glebm** [comment]
Tracking DB text search in #172

**Comment by jayroh** [comment]
Of the items in the list above the only one left is to open source the thredded.com codebase. I don't think I'm ready for that yet but I could certainly see that being something we could do once that gets updated to use the latest version of this gem. That codebase is old as dirt too so I'll likely have to do a little scrubbing of the history.

That being said. On the road to 1.0 we'll have to make, what? One more release? `0.2.0`?

Between 0.2.0 and 1.0 I'd love to get thredded.com updated so that it's a good representation of what people would be using.

Thoughts? Anyone? Bueller?

**Comment by glebm** [comment]
If upgrading thredded.com is difficult, why not write a super-simple app from scratch? A very simple app that just bundles together Devise (or Sorcery) and Thredded.

**Comment by jayroh** [comment]
Not a bad idea. That's probably the better route

**Comment by glebm** [comment]
@jayroh How about we run `spec/dummy`? While not "real", it actually gives more insight into Thredded. Perhaps it can run on `demo.thredded.com`? Then we can launch :)

**Comment by jayroh** [comment]
I'll get to work on being able to deploy the dummy app to heroku. Should actually be superior bc then the db can be wiped and re-seeded semi-daily.

**Comment by glebm** [comment]
Nice! :+1:

**Comment by jayroh** [comment]
Getting a dummy app in a rubygem to run on heroku is a complete and utter pain. I hesitate to say catastrophe but it's taken me almost all night just to not get a 500 error.

**Comment by jayroh** [comment]
Will keep the conversation running here from that PR, actually. We're almost there - knocking down these blockers :)

Question now, is - thredded.org or thredded.io

`.io` seems to be de rigueur these days so I'm kinda leaning to that. @glebm @TheDudeWithTheThing  - what do you think? I have both registered, so ¯\_(ツ)_/¯

**Comment by glebm** [comment]
I don't have a strong opinion, but would prefer `org`. 

Legally, In order to register `.io` domains you need not be registered or established in the British Indian Ocean territory. http://www.nic.io/rules.html

**Comment by jayroh** [comment]
That's as good a reason as any.

**Comment by jayroh** [comment]
http://thredded.org  - Good to go. 

Cloudflare set up.
Rack-canonical-host set up to force the naked domain.

**Comment by glebm** [comment]
Awesome, I've enabled `force_ssl` as well and deployed. I've updated the homepage with a summary of Thredded features in #241, because I think the demo app is what we'll share on HN et all (or many people may not notice the demo).

**Comment by glebm** [comment]
Oops, setting force_ssl killed it, investigating.

**Comment by glebm** [comment]
@jayroh Can you try switching on "Full SSL" in CloudFlare? http://stackoverflow.com/questions/32956705/force-ssl-redirect-loop-on-rails-4-using-cloudflare-ssl

**Comment by jayroh** [comment]
Ah haha yup. Force SSL and cloudflare are an infinite loop nightmare

To the client, it's SSL. To the passthru server (Heroku) it is not. So it
keeps redirecting

**Comment by jayroh** [comment]
Could do a "force ssl" with JavaScript? Certainly not as elegant as the
middleware level solution - but it works and leverages the free plan with
cloudflare

**Comment by glebm** [comment]
Is "Full SSL" not available on the free tier?

**Comment by glebm** [comment]
There are other ways to check on the server side that I can look into if that's the case. Can you give me access to the CloudFlare account so I can have a look?

**Comment by jayroh** [comment]
Just enabled it (I think)

I'm on my phone so I'm not 100% sure their weird UX took it but I think
it's set

**Comment by glebm** [comment]
OK, trying force_ssl again

**Comment by glebm** [comment]
It works! :smile:

**Comment by jayroh** [comment]
Well holy shit.

I need this for another app!

**Comment by glebm** [comment]
I must say the demo app looks amazing. Especially on a phone.

**Comment by glebm** [comment]
The design is much cleaner than Discourse.

 :beers:

**Comment by glebm** [comment]
Saturday morning is the best time to post something on HN, apparently. The idea is to post an article, then send a link to /new to all your friends and tell them to upvote. My stuff has gone to the frontpage a few times this way ;)

**Comment by jayroh** [comment]
Let's shoot for next Saturday then? That gives us some time to button a few
more things up and start the HYPE MACHINE

I was just thinking we should get a checklist together with some further
todo's - places to submit to, analytics, etc. I think there are just a very
few things left :)

**Comment by glebm** [comment]
:+1: for a checklist. We should also tag v0.3.0 and change README to use a version instead of master before Saturday.

**Comment by jayroh** [comment]
@glebm @TheDudeWithTheThing would love a look at the checklist above in the original issue post. I figured I would keep everything here in this issue instead of spinning up a new one. @glebm apologies for hijacking your post content :)

As far as text and copy - I can start a google doc and we can throw whatever we need to in there.

![](https://media.giphy.com/media/vv41HlvfogHAY/giphy.gif)

**Comment by glebm** [comment]
>  Analytics code in demo app. Mixpanel? Google Analytics?

I'd lean with Google Analytics because it's 100% reliable, stable, and fast. Mixpanel has some more advanced tracking options which we don't need.

**Comment by glebm** [comment]
Another one: 
* [ ] Upgrade Heroku to one of the paid tiers and scale up before release, because the free tier won't survive HN traffic. Does the donations war chest need topping up?

**Comment by jayroh** [comment]
That's a good idea. As it may scale up and/or down - we can handle it. I'm
not too worried about it.

**Comment by jayroh** [comment]
How do you guys feel about tagging 0.3.0 today (Thursday)? Anything blocking it?

Do we have a 0.2.2 -> 0.3.0 migration task yet, actually?

**Comment by glebm** [comment]
Yeah, let's do it! We don't have a migration task yet. A task would be nice, though we can also just document where the upgrade migrations are a la https://github.com/comfy/comfortable-mexican-sofa/wiki/Upgrading-ComfortableMexicanSofa.

**Comment by jayroh** [comment]
ALRIGHT.

Everything is built and pushed to rubygems, deployed .org and .com - I guess I'll start the dog and pony show tomorrow :)

**Comment by glebm** [comment]
:+1:

**Comment by glebm** [comment]
A high HN karma poster (mine is 145) should submit in about two hours.

**Comment by jayroh** [comment]
Go for it! Let us know and I'll unleash whatever people I can

**Comment by glebm** [comment]
@jayroh Pinged you on Hangouts

**Comment by glebm** [comment]
OK, it's up! Go to https://news.ycombinator.com/newest and upvote Thredded! :tada:

**Comment by glebm** [comment]
Didn't get it on the frontpage of HN but we'll just have to try again later.
Also posted on lobste.rs: https://lobste.rs/recent

**Comment by jayroh** [comment]
@glebm do you have any invites for lobste.rs? Would love to get in over there
