### ISSUE TITLE
Remove jquery dependency

### ISSUE THREAD

**Issue by glebm** [thredded/thredded#593]
jQuery is well over half the total size of Thredded JavaScript and there is not much need for jQuery in our code.

* [x] Thredded components https://github.com/thredded/thredded/commit/9da4b0204f4ce3e5c871af4ed11ec0c312991a07 https://github.com/thredded/thredded/commit/ed45acdb46985985cefedc2d9b222bcc2e2c7434

Dependencies:
* [x] select2 -> [textcomplete](https://github.com/yuku-t/textcomplete), split by commas. #597 
  Other alternatives considered and rejected:
  * [Choices](https://github.com/jshjohnson/Choices) 16.4 KiB gz (https://unpkg.com/choices.js@2.8.3)
  * [Selectivity](https://github.com/arendjr/selectivity) 16.6 KiB gz ([v3.0.4](https://github.com/arendjr/selectivity/releases/tag/3.0.4))
  * datalist populated via [xhr](https://www.raymondcamden.com/2012/06/14/example-of-a-dynamic-html5-datalist-control) + [a datalist polyfill](https://www.npmjs.com/package/datalist-polyfill) - 1.7 KiB gz.
   No multiple selection, as only `input type="email"` supports it.
* [x] [jquery.textcomplete](https://github.com/yuku-t/jquery-textcomplete) -> [textcomplete](https://github.com/yuku-t/textcomplete) 6.5 KiB gz #596
* [x] jquery_ujs -> rails-ujs #592 
* [x] jquery.timeago -> timeago.js #591 
* [x] jquery.autosize -> autosize https://github.com/thredded/thredded/commit/1023c21598575d51f8cd4448251f447c47cefa8f

**Comment by glebm** [comment]
JS size before: 66.7 KiB gzipped.

**Comment by glebm** [comment]
JS size after: 22.4 KiB gzipped.
